[package]
name = "lardum"
version = "0.1.0"
authors = ["Matthew Fisher <matt.fisher@fishworks.io>"]
edition = "2018"

[dependencies]
tcod = { git = "https://github.com/tomassedovic/tcod-rs", features = ["serialization"] }
rand = "0.8"
serde = "1"
serde_derive = "1"
serde_json = "1"
